apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: node-artifact-test
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: artifactory-artifactory-jcr.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap-docker-local/raisa28jan:9de8c495c615d27bf41d17ba33d3fbd245d3ba82@sha256:eaf728ddf023889aad9a2f3d0af1738523b57b8b4b443adbc3f34f6bc4b68031
          name: container-image
